"""Add notification_sent to events

Revision ID: 9bbf022d1813
Revises: d0a9494ac2eb
Create Date: 2026-03-13 08:48:36.537261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bbf022d1813'
down_revision: Union[str, Sequence[str], None] = 'd0a9494ac2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('events', sa.Column('notification_sent', sa.Boolean(), nullable=True, comment='Whether a reminder email has been sent for this event'))
    
    # Update existing rows to False
    op.execute("UPDATE events SET notification_sent = FALSE")
    
    # Now set as NOT NULL
    op.alter_column('events', 'notification_sent', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'notification_sent')
    # ### end Alembic commands ###
