"""Add chat_messages table

Revision ID: d0a9494ac2eb
Revises: 
Create Date: 2026-03-13 08:45:47.817763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a9494ac2eb'
down_revision: Union[str, Sequence[str], None] = 'f6d8a37e1b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='user | assistant'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.alter_column('calendar_syncs', 'google_calendar_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Google Calendar ID (default: primary)',
               existing_nullable=False,
               existing_server_default=sa.text("'primary'::character varying"))
    op.alter_column('calendar_syncs', 'google_event_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Event ID in Google Calendar',
               existing_nullable=True)
    op.alter_column('calendar_syncs', 'sync_status',
               existing_type=sa.VARCHAR(length=20),
               comment='synced | pending | error',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('calendar_syncs', 'sync_error',
               existing_type=sa.TEXT(),
               comment='Last sync error message',
               existing_nullable=True)
    op.alter_column('calendar_syncs', 'etag',
               existing_type=sa.VARCHAR(length=255),
               comment='Google Calendar event etag for conflict detection',
               existing_nullable=True)
    op.drop_index(op.f('ix_calendar_syncs_event_id'), table_name='calendar_syncs')
    op.alter_column('events', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               comment='Original timezone of the event',
               existing_nullable=False,
               existing_server_default=sa.text("'America/Sao_Paulo'::character varying"))
    op.alter_column('events', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='active | cancelled',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('users', 'domain',
               existing_type=sa.VARCHAR(length=255),
               comment='Google Workspace domain (hd claim)',
               existing_nullable=True)
    op.alter_column('users', 'google_refresh_token',
               existing_type=sa.TEXT(),
               comment='Encrypted refresh token for Calendar sync',
               existing_nullable=True)
    op.drop_constraint(op.f('users_google_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_unique_constraint(op.f('users_google_id_key'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'google_refresh_token',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Encrypted refresh token for Calendar sync',
               existing_nullable=True)
    op.alter_column('users', 'domain',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Google Workspace domain (hd claim)',
               existing_nullable=True)
    op.alter_column('events', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='active | cancelled',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('events', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='Original timezone of the event',
               existing_nullable=False,
               existing_server_default=sa.text("'America/Sao_Paulo'::character varying"))
    op.create_index(op.f('ix_calendar_syncs_event_id'), 'calendar_syncs', ['event_id'], unique=False)
    op.alter_column('calendar_syncs', 'etag',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Google Calendar event etag for conflict detection',
               existing_nullable=True)
    op.alter_column('calendar_syncs', 'sync_error',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Last sync error message',
               existing_nullable=True)
    op.alter_column('calendar_syncs', 'sync_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='synced | pending | error',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('calendar_syncs', 'google_event_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Event ID in Google Calendar',
               existing_nullable=True)
    op.alter_column('calendar_syncs', 'google_calendar_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Google Calendar ID (default: primary)',
               existing_nullable=False,
               existing_server_default=sa.text("'primary'::character varying"))
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
